import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Toaster } from "sonner";
import Navbar from "@/components/navbar/navbar";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx("min-h-screen h-screen text-slate-800", font.className)}
      >
        <Toaster />
        <Navbar />
        <div className="pt-20 px-4 h-full flex flex-grow pb-4">{children}</div>
      </body>
    </html>
  );
}
